import path from "node:path";
import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // Pin the workspace root; a stray lockfile in the parent folder otherwise
  // makes Turbopack guess wrong.
  turbopack: { root: path.resolve(import.meta.dirname) },
  // GitHub Pages serves plain files, so the whole site is prerendered to HTML at build time.
  output: "export",
  reactStrictMode: true,
  agentRules: false,
  images: {
    // The Image Optimization API needs a server; variants are generated by scripts/optimize-images.mjs.
    unoptimized: true,
  },
};

export default nextConfig;
